### ISSUE TITLE
Potential 5-10x Speedup in boards.play

### ISSUE THREAD

**Issue by sethtroisi** [mattheww/sgfmill#1]
Board.play can be dramatically speedup by only looking for surrounded groups starting at (row, col).
Are you open to a clean pull request?

**Comment by mattheww** [comment]
Sure.

That board implementation started out as part of the testsuite for my native-code implementation, so it was deliberately simpleminded, and it recalculated all the groups from scratch after each move so they could be compared with the incremental bookkeeping.

There's no good reason for sgfmill's board implementation to have those properties.

**Comment by sethtroisi** [comment]
Any chance you could take a look at #2? I'd love to get it merged

**Comment by mattheww** [comment]
Hi, sorry for going quiet. I haven't forgotten!

I should have some time this weekend to sort this out.

**Comment by mattheww** [comment]
This is in v1.1.1 .
