### ISSUE TITLE
Always get a messy code or None when the game player has a Japanese or Chinese name

### ISSUE THREAD

**Issue by songsenand** [mattheww/sgfmill#4]
Your work is awesome. Thanks a lot.
However, I have noticed that I'll get a messy code or `None`  if the player in the SGF file has a Japanese or Chinese name.
Like that:
SGF file content:
![sgf file content](https://user-images.githubusercontent.com/13940907/43619680-9f317b54-9701-11e8-9cd9-6bd05c7d634a.png)

and the codes

```python
from sgfmill import sgf
with open('00006.sgf', 'rb') as f:
    game = sgf.Sgf_game.from_bytes(f.read())
root = game.get_root()
print((root.get('RE')))
print(root.get('PB'))
print(game.get_winner())
print(game.get_player_name('w'))

```
I'll get
```
ºÚ²»¼ÆµãÊ¤
ÄôÎÀÆ½
None
Âó¿ËÀ×ÃÉ
```

Did you have a plan to fix it? 
Or did you mind if I do something for your library?

**Comment by mattheww** [comment]
Short answer:

I expect you will get what you want if you replace

    sgf.Sgf_game.from_bytes(f.read())

with

    sgf.Sgf_game.from_bytes(f.read(), override_encoding="utf-8")

**Comment by mattheww** [comment]
Longer answer:

An SGF file is supposed to use the `CA` property to indicate its encoding, and (because SGF is old) the default encoding is `iso-8859-1`.

So if you are generating the SGF file yourself, it would be best to add `CA[UTF-8]`, and if you are getting it from somewhere else it would be good to ask them to do that.

Maybe it would make sense for `Sgf_game.from_bytes()` to support a `default_encoding` parameter so that users could say that files which don't provide `CA` should be treated as `utf-8`, without having to override `CA` if it *was* included.

**Comment by songsenand** [comment]
Thank you!

**Comment by SatinWukerORIG** [comment]
`File "/home/satinwuker/learn/sai/sai.py", line 15, in <module>
    b_player = root_node.get("PB")
  File "/home/satinwuker/.local/lib/python3.9/site-packages/sgfmill/sgf.py", line 178, in get
    return self._presenter.interpret(
  File "/home/satinwuker/.local/lib/python3.9/site-packages/sgfmill/sgf_properties.py", line 681, in interpret
    return self.interpret_as_type(
  File "/home/satinwuker/.local/lib/python3.9/site-packages/sgfmill/sgf_properties.py", line 657, in interpret_as_type
    return property_type.interpreter(raw, self)
  File "/home/satinwuker/.local/lib/python3.9/site-packages/sgfmill/sgf_properties.py", line 223, in interpret_simpletext
    return sgf_grammar.simpletext_value(bb).decode(context.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 0: invalid start byte`
@mattheww override_encoding is not working
I did the same thing as you said, but no use.

**Comment by mattheww** [comment]
@SatinWuker if you attach an SGF file that's causing trouble to this issue, or upload it to somewhere public, I can have a look at what the problem is.

**Comment by SatinWukerORIG** [comment]
@mattheww It is okay, I solved the problem by changing "UTF-8" to GB18030
