### ISSUE TITLE
Help with new_child() in a given index

### ISSUE THREAD

**Issue by smolendawid** [mattheww/sgfmill#5]
```
o
|
o
|   
o  
|
o
```

Hi! Let's say this is my sequence made of four moves (first column). I created it using
```
         node = game.extend_main_sequence()
         node.set_move(color, move)
```

Now I want to add a second variation (make 3rd move different) and continue in this variation.

```
o
|
o
|  \
o   o
|   |
o   o
    |
    o
```

So I'm trying like that:
```
            node = game.get_root()
            child_node = node.new_child(index=2)
            child_node = set_move(color, move)
```

But it's not working and I can't get why. In Sabaki GUI I can see that a node is added at the beginning. I attach the screenshot from the Sabaki, _index_ is set to 6 and main sequence is longer. 

<img width="79" alt="Zrzut ekranu 2020-04-19 o 12 47 28" src="https://user-images.githubusercontent.com/9264154/79685853-0dd60580-823c-11ea-8033-fa6fec825ca0.png">

@mattheww I would appreciate your tip.

**Comment by smolendawid** [comment]
The minimal code that adds node in the first position instead if _2_

from sgfmill import sgf
```

game = sgf.Sgf_game(size=19, encoding="UTF-8")

node = game.extend_main_sequence()
node.set_move('b', (0,0))
node = game.extend_main_sequence()
node.set_move('w', (0,1))
node = game.extend_main_sequence()
node.set_move('b', (0,2))
node = game.extend_main_sequence()
node.set_move('w', (0,3))

node = game.get_root()
child_node = node.new_child(index=2)
child_node.set_move('w', (10, 0))

with open('game.sgf', 'w') as f:
    f.write(game.serialise().decode("utf-8"))

```

**Comment by mattheww** [comment]
The `index` parameter to `new_child()` is for controlling the order of variations, not for controlling which node a variation starts from.

That is, in your diagrams it's controlling the horizontal position not the vertical position.

The variation starts from the node that you call the `new_child()` method on.

So I think you could get the result you want like this:

````
node1 = game.extend_main_sequence()
node1.set_move('b', (0,0))
node2 = game.extend_main_sequence()
node2.set_move('w', (0,1))
node3 = game.extend_main_sequence()
node3.set_move('b', (0,2))
node4 = game.extend_main_sequence()
node4.set_move('w', (0,3))

child_node = node2.new_child()
child_node.set_move('w', (10, 0))
````

Or like this:

````
node = game.extend_main_sequence()
node.set_move('b', (0,0))
node = game.extend_main_sequence()
node.set_move('w', (0,1))
node = game.extend_main_sequence()
node.set_move('b', (0,2))
node = game.extend_main_sequence()
node.set_move('w', (0,3))

node = game.get_main_sequence()[1]
child_node = node.new_child()
child_node.set_move('w', (10, 0))
````

**Comment by smolendawid** [comment]
Thank you for the clarification! I couldn't figure it out. I think it's a very useful example and could be listed in examples.
